### ISSUE TITLE
Street lamp 105-7935 near 1801 Park Avenue is out

### ISSUE THREAD

**Issue by partytax** [livable-lynchburg/lynchburg-road-issues#173]
https://www.openstreetmap.org/#map=19/37.40521/-79.15742

![signal-2024-02-21-210845_002](https://github.com/Lynchburg-Urban-Network/lynchburg-road-issues/assets/29897671/1aaefb7a-da97-4fd4-b619-e7218e2e37db)

**Comment by partytax** [comment]
Reported to APCO through web form

**Comment by partytax** [comment]
Received response:


> 
> Dear Nathan Wyand,    
> 
>  
> 
> Thank you for contacting us at AppalachianPower.com.  
> 
>  
> 
> Regrettably, lights located on the apartment complex property, need to be reported to the property manager of this apartment community to request repair of the light at 1801 Park Ave.
> 
> We apologize for any inconvenience.
> 
>  
> 
> Did you know that you have access to other online transactions and features with AEP such as outage reporting, home energy calculators, and energy saving tips? Please visit AEP.com to learn about your online options.
> 
>  
> 
> If we can be of any further assistance, you are welcome to email us at customer_service@AEP.com.  When emailing us, please include a copy of the original inquiry and subsequent responses.
> 
>  
> 
> Sincerely,
> 
>  
> 
> Robbi N.
> 
> AEP Customer Service® Dear Nathan Wyand,    
> 
>  
> 
> Thank you for contacting us at AppalachianPower.com.  
> 
>  
> 
> Regrettably, lights located on the apartment complex property, need to be reported to the property manager of this apartment community to request repair of the light at 1801 Park Ave.
> 
> We apologize for any inconvenience.
> 
>  
> 
> Did you know that you have access to other online transactions and features with AEP such as outage reporting, home energy calculators, and energy saving tips? Please visit AEP.com to learn about your online options.
> 
>  
> 
> If we can be of any further assistance, you are welcome to email us at customer_service@AEP.com.  When emailing us, please include a copy of the original inquiry and subsequent responses.
> 
>  
> 
> Sincerely,
> 
>  
> 
> Robbi N.
> 
> AEP Customer Service®

**Comment by partytax** [comment]
Responded:


>Are you sure? 105-7935 is a standalone street lamp located between the sidewalk and the road.

**Comment by TimMagee** [comment]
![IMG_20240904_200425_244](https://github.com/user-attachments/assets/b318d543-febd-4a06-a699-c0617214e59b)

This lamp is now working.
