### ISSUE TITLE
Unmarked street lamp beside post office on 12th Street is out

### ISSUE THREAD

**Issue by partytax** [livable-lynchburg/lynchburg-road-issues#177]
https://www.openstreetmap.org/#map=19/37.41109/-79.14259

![signal-2024-02-24-214729_002](https://github.com/Lynchburg-Urban-Network/lynchburg-road-issues/assets/29897671/f347fe75-63c2-48f1-928c-a104515bbd03)

**Comment by partytax** [comment]
When you submit, mention that it is tagged with blue electrical tape.

**Comment by partytax** [comment]
Reported to APCO through web form

**Comment by partytax** [comment]
Received response the other day:

> Dear Nathan Wyand,
> 
> Thank you for contacting us at AppalachianPower.com.
> 
> We have reported the street light out at 1100 Clay Street. The order number is 022764715. We appreciate you bringing this to our attention and will investigate as soon as possible.
> 
> If we can be of any further assistance, you are welcome to email us at customer_service@AEP.com. When emailing us, please include a copy of the original inquiry and subsequent responses.
> 
> Sincerely,
> 
> Heather M.
> Appalachian Power®
>  
> CONNECT               
> "This message, including any attachments, contains confidential information intended for a specific individual and purpose, and is protected by law. If you are not the intended recipient, you should delete this message and are hereby notified that any disclosure, copying, or distribution of this message, or taking any action based on it is strictly prohibited."
>

**Comment by TimMagee** [comment]
![IMG_20240904_201334_750](https://github.com/user-attachments/assets/c772c181-6d82-4bb0-9847-bf045d2642dd)
This lamp is now working.
