### ISSUE TITLE
Inbound bus stop at 8th Street and Harrison Street not associated with route 3B in GTFS file or Transit App

### ISSUE THREAD

**Issue by TimMagee** [livable-lynchburg/lynchburg-road-issues#188]
There is a bus stop at 12th/Harrison Outbound and Inbound. Only outbound stop is associated with route 3B in the GTFS file.

Looked in the GTFS data and discovered it is stop **785978** with the name of **8th St. & Harrison St. (Inbound)**. It is one of about 14 stops in the [January 2023 GTFS file](https://gltconline.com/gltc-gtfs-zip-1-31-2023/) that have no route associated with them.

![IMG_20240331_181801334_HDR](https://github.com/Lynchburg-Urban-Network/lynchburg-road-issues/assets/11220851/c2208f01-0e8a-4f37-9062-646a68f19cc4)

**Comment by partytax** [comment]
Considered that this January 2023 GTFS file I'm using is really old. Emailed Josh Moore (manager) to inquire about where I can get a more up-to-date file and who I can contact directly RE data issues.

**Comment by partytax** [comment]
Reached out to Wendell Watts to get this updated:

>While I have you, could you associate stop 785978 (8th St. and Harrison St. Inbound) with route 3B? It appears to be an orphaned stop in the data, but a sign really exists there.
>
>Nathan

**Comment by partytax** [comment]
Downloaded latest GTFS from website and it's the same file they had published in April of this year. This has not been fixed, obviously. Asked some group members to check their Transit App to see if the error had been caught and fixed on their side. It had not.

Following up with Wendell Watts II to inquire about what's going on here:

>Good morning. Just following up on this request to associate orphaned stop 785978 at 8th and Harrison with route 3B inbound. I downloaded the GTFS data today and noticed it had not been fixed. Thanks in advance for your help!
>
>Nathan

**Comment by partytax** [comment]
Received response the other day:

> 
> Hi Nathan,
> 
> I've checked into this and have everything correct on my side. For some reason this stop isn't coming up in the feed. I am in contact with Trillium to get to the bottom of this.
> 
> Thanks,
> 
> image  
> 
>    Wendell Watts, II                  
> 
>    Operations Assistant | (o) 434.485.8329 | (f) 434.528.4582
> 
>  
> 
> Greater Lynchburg Transit Company
> 
> 419 Bradley Drive ● Lynchburg, Virginia 24501 | P.O. Box 11286 ● Lynchburg, Virginia 24506

**Comment by partytax** [comment]
Fixed in latest GTFS: http://gltconline.com/wp-content/uploads/2024/10/gltc-lynchburg-va-us-OCT24.zip
