### ISSUE TITLE
Unmarked street lamp on 12th Street in front of USPS parking lot is out

### ISSUE THREAD

**Issue by partytax** [livable-lynchburg/lynchburg-road-issues#33]
https://www.openstreetmap.org/#map=19/37.41123/-79.14235
![signal-2023-04-05-213057_002](https://user-images.githubusercontent.com/29897671/235911834-fa6e0450-1768-4310-aad8-c1ff29e07f1c.jpeg)

**Comment by partytax** [comment]
Verified that it's still out on 2023-08-01.

Reported to APCO 2023-08-02.

**Comment by partytax** [comment]
Waiting for APCO email confirmation.

**Comment by partytax** [comment]
Received APCO email confirmation:
```
Dear Nathan Wyand,

 

Thank you for contacting us at AppalachianPower.com.

 

We have reported the street light out at 413 12th Street. The order number is 029994939. We appreciate you bringing this to our attention and will make repairs as soon as possible.

 

If we can be of any further assistance, you are welcome to email us at customer_service@AEP.com. When emailing us, please include a copy of the original inquiry and subsequent responses.

 

Sincerely,

 

Ashley C.

Appalachian Power®

 

CONNECT              

"This message, including any attachments, contains confidential information intended for a specific individual and purpose, and is protected by law. If you are not the intended recipient, you should delete this message and are hereby notified that any disclosure, copying, or distribution of this message, or taking any action based on it is strictly prohibited."
```

**Comment by partytax** [comment]
Made personal task to determine if lamp is still out

**Comment by partytax** [comment]
Checked and lamp is still out. Responded to APCO email to check status:

```
Please provide me with the status of order 022645243. I checked this morning and the lamp is still out. Thank you.
```

**Comment by partytax** [comment]
Received response from APCO:
```

Dear Nathan Wyand,

 

Thank you for contacting us at AppalachianPower.com.

 

We understand your concern. The light in question has an underground wire that must be repaired. We are unable to guarantee a date the repairs will be completed; however, we will attempt to complete repairs as quickly and safely as possible. We apologize for any inconvenience.

If we can be of any further assistance, you are welcome to email us at customer_service@AEP.com. When emailing us, please include a copy of the original inquiry and subsequent responses.

Sincerely,

Matthew M.
Appalachian Power®
 

CONNECT
	

	

	

	

"This message, including any attachments, contains confidential information intended for a specific individual and purpose, and is protected by law. If you are not the intended recipient, you should delete this message and are hereby notified that any disclosure, copying, or distribution of this message, or taking any action based on it is strictly prohibited."

```

**Comment by partytax** [comment]
Made personal task to check if lamp is still out

**Comment by partytax** [comment]
Added to personal task to try to infer lamp ID from surrounding lamps

**Comment by partytax** [comment]
Verified that lamp is still out. No adjacent lamps have pole numbers! Requesting status update on order from APCO:

>Please provide me with the status of order 029994939. The lamp is still out as of 2 days ago. Unfortunately the lamp has no pole number, so I have marked the lamp with blue electrical tape to guide technicians to the right lamp.
Thank you for your time!

**Comment by partytax** [comment]
Received response:

>Dear Nathan,
Thank you for contacting us at AppalachianPower.com. 
We understand your concern. The light in question has additional components that must be repaired. We are unable to guarantee a date the repairs will be completed; however, we will attempt to complete repairs as quickly and safely as possible. We apologize for any inconvenience.
If we can be of any further assistance, you are welcome to email us at customer_service@AEP.com. When emailing us, please include a copy of the original inquiry and subsequent responses.
Sincerely,
Matthew M.
Appalachian Power®

**Comment by partytax** [comment]
Made task to check if lamp still out.

**Comment by TimMagee** [comment]
![IMG_20240904_201216_486](https://github.com/user-attachments/assets/50f97b50-8769-4a4e-9440-86c3d34c1bd8)
That lamp is now working.
